### PR TITLE
Simplify ingest Rundown to local Sofie environment

### PR DESCRIPTION
**Pull request by LindvedKrvang**
Simplify commands for convert.js 
Possible to specify another studioId for upload script

### CODE REVIEW

**Review by ianshade — CHANGES_REQUESTED** [review]
We're loosing the ability to upload rundowns under different file names. IMO only the upload.sh should be changed, so that it can takes the following arguments:
- rundown file path (required)
- studio ID (optional, defaults to `studio0`)

Or maybe we could also have one extra parameter:
- Sofie host (optional, host and port combined, defaults to `localhost:3000`)

This way we could easily ingest such rundowns for testing purposes in Zero, or any gallery, without the need to go through iNews

**Comment by LindvedKrvang** [comment]
The idea was the to make it as simple as possible. Personally, it would be nice not having to always specify the "intermediary" json file. 
What do you think about adding the argument for the output.json as optional as well?

**Comment by ianshade** [comment]
Okay, let's make both optional: the output path of convert.js, and the input for upload.sh. The default name should probably be something like `converted-rundown.json`, or `converted.json`. And please add that name to .gitignore so that it doesn't bother us when committing or doesn't get committed accidentally.

**Comment by LindvedKrvang** [comment]
Updated the PR

**Review by ianshade — APPROVED** [review]
I like it! README.md probably needs updating before merging

**Pull request merged**
